version: '3'
services:
  sft-action-marketplace:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - config/docker.properties
    expose:
      - "8081"
    ports:
      - "8081:8081"
